[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_solsplits = "4pCvQPP2gqbJg56xehy8XmMo98u5DhK6yrGtLGznfmAg"

[programs.devnet]
anchor_solsplits = "4pCvQPP2gqbJg56xehy8XmMo98u5DhK6yrGtLGznfmAg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
